### ISSUE TITLE
Add requirement.txt

### ISSUE THREAD

**Issue by rpanai** [dexplo/bar_chart_race#1]
First of all thank you for this contribution! We needed this on python too.

Do you mind to add a `requirement.txt` in your main?

```bash
# requirement.txt
pandas
numpy
matplotlib
```
I'm now writing a conda package for this library but in case you change some dependencies have them in a file will be easier to manage.

**Comment by jonolsu** [comment]
If you want to list dependencies it might be better to add this to the setup.py file.  If you do so, it will check and install dependencies if they aren't met during the "pip install ...." process.  Here is an example of the code that can go in the file:

```
install_requires = [
    'pandas>=0.23.4',
    'SQLAlchemy>=1.3.1',
    'requests>=2.22.0',
    'pyodbc>=4.0.27',
    'openpyxl>=3.0.3',
]
setuptools.setup(
    name="bar_chart_race",
    version="0.0.6",
    author="Ted Petrou",
    author_email="petrou.theodore@gmail.com",
    description="Create animated bar chart races using matplotlib",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/dexplo/bar_chart_race",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
    ],
    install_requires=install_requires,
)

```
I can't promise this works exactly as-is, but that's what I've done to create installable packages in the past.

**Comment by tdpetrou** [comment]
@rpanai The next version will have a `install_requires` parameter added to its setup as @jonolsu mentioned. That should work correct?

**Comment by rpanai** [comment]
I guess so. I'll check this out and I'm going to modify the recipe accordingly.

**Comment by rpanai** [comment]
I think that you should add `dateutil` too as the conda recipe is not working because of this error

```
ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'
```

**Comment by tdpetrou** [comment]
Thanks for continuing to check up on this. I've never touched conda feedstock before, but from clicking on the errors, I see `no module named pandas` in the 'Run docker build'. 

I notice that the `meta.yaml` is missing `--no-deps` in the `build: script` line. 

<img width="955" alt="Screen Shot 2020-06-01 at 6 37 00 PM" src="https://user-images.githubusercontent.com/7226751/83461533-fbeca280-a436-11ea-9659-42168d27741d.png">


pandas should take care of the dateutil dependency.
