### ISSUE TITLE
Two errors executing GitHub example ([1]cmap color [2]AttributeError: 'Rectangle' object has no property 'fixed_order')

### ISSUE THREAD

**Issue by leifulstrup** [dexplo/bar_chart_race#11]
This is working fine:
bcr_html = bcr.bar_chart_race(df=df, filename=None)
display(HTML(bcr_html))

However, tried the featured example on Github and got two errors. Error 1:

[1] dark12 not found in cmap. Changed that to Dark2. (working)

[2} AttributeError: 'Rectangle' object has no property 'fixed_order'

Not clear how to fix the second error

**Comment by tdpetrou** [comment]
I think you are not on the latest version.

Can you run `bcr.__version__`. It should read 0.1.0

**Comment by leifulstrup** [comment]
Operator Error on my part. Had not updated to the latest version of the package. Works now.
