### ISSUE TITLE
Can it run without FFMPEG?

### ISSUE THREAD

**Issue by etjkai** [dexplo/bar_chart_race#13]
```
Exception: You do not have ffmpeg installed on your machine. Download
                            ffmpeg from here: https://www.ffmpeg.org/download.html.
```

I'm trying to run the example code as shown in the README.md, however, I'm getting the above error.

I am on Windows, and have already installed ffmpeg, and included it in my Path variables.

Is there anyway to run without ffmpeg?

**Comment by tdpetrou** [comment]
This error message could be wrong. Also, setting `writer` to `'html'` might not use ffmpeg

**Comment by etjkai** [comment]
Thank you, I've restarted my computer and have managed to get it to work. 

As a beginner Python user, I have to say that the `bar_chart_race` method was very well documented, and enabled me to create many cusomizations to the requirements. 

I'd assume that there is an option to change the background of the chart as well right? Might have not chanced across that parameter as of yet.
