### ISSUE TITLE
AttributeError: module 'bar_chart_race' has no attribute 'prepare_long_data'

### ISSUE THREAD

**Issue by WambuguGichuki** [dexplo/bar_chart_race#14]
AttributeError                            Traceback (most recent call last)
<ipython-input-88-01cd4867684d> in <module>
      `<1 import bar_chart_race as bcr
      2 
----> 3 change_values,change_ranks = bcr.prepare_long_data(change2,index = "week",columns = "Location",values = "Amount Spent",steps_per_period=1)
      4 
      5 `change_values.head()>````

**Comment by tdpetrou** [comment]
Can you make sure you upgrade to the most recent version? Thanks!
