### ISSUE TITLE
Bar Label Formatting

### ISSUE THREAD

**Issue by vperlerin** [dexplo/bar_chart_race#16]
Excellent work!
It looks like it isn't possible to format the Bar Labels while it's sometimes necessary to display float.

**Comment by tdpetrou** [comment]
Thanks for bringing this up! Definitely an oversight and an easy feature to add. I'll make it available in the next release, which should be out next week.

**Comment by tdpetrou** [comment]
Just added this change on master. There will be new parameters `bar_label_position` and `bar_label_format`

**Comment by vperlerin** [comment]
Thank you!
