### ISSUE TITLE
Bar labels only show integers but floats

### ISSUE THREAD

**Issue by tianrenmaogithub** [dexplo/bar_chart_race#17]
Hi. Thank you for developing it. 
I need to show percentages next to the bars but it only showed integers rather than floats. Can you add an option to change the format? 
Also, the ticks have no shading color and they will overlie each other when they meet and people can see neither. Can you add shading color so people can see at least one of them? Thank you.

**Comment by tdpetrou** [comment]
Yes! I made this change in #16. New release coming soon (next week).
