### ISSUE TITLE
Specify fixed color to Bars

### ISSUE THREAD

**Issue by sathyamoorthyrr** [dexplo/bar_chart_race#19]
In my use case, I want to use custom colors **per** bar.

So, altogether I wanna use only two colors for my bars.

Tried to use the following in my chart which has 14 bars,
`cmap = (["green"] * 7) + (["red"] * 7)`

Great! this assigns the colors to bars in Order too!

**Comment by tdpetrou** [comment]
Yes, that's how you do it!
