### ISSUE TITLE
Include license in source distribution

### ISSUE THREAD

**Issue by synapticarbors** [dexplo/bar_chart_race#2]
It would be helpful to include the license file in the source distribution. I've seen this done by using a `MANIFEST.in` file, but there are other mechanisms as well. 

Also as a side note, the meta data in the `setup.py` says this package uses a BSD license, but the license says MIT: https://github.com/dexplo/bar_chart_race/blob/master/setup.py#L23

**Comment by tdpetrou** [comment]
Thanks for bringing this up. I've included the license and corrected the setup.py to say MIT now.
