### ISSUE TITLE
Pause for certain time after every data row is displayed

### ISSUE THREAD

**Issue by sathyamoorthyrr** [dexplo/bar_chart_race#20]
Is that possible to pause the animation for 1 or 2 secs after every row of data is displayed?

**Comment by tdpetrou** [comment]
Yes, it would be possible to add a delay at the end of each period. Maybe a parameter like `delay` or `end_period_delay` could work. Not a bad idea. Let me think about it some more.

**Comment by sathyamoorthyrr** [comment]
thanks, it, might become a most sought after feature

**Comment by tdpetrou** [comment]
The more I think about it, the more it makes sense. I'm going to add it now.

**Comment by tdpetrou** [comment]
Just added this. Will be in the next release. Thank you @sathyamoorthyrr for the idea!

**Comment by sathyamoorthyrr** [comment]
@tdpetrou give me some tips to add silent audio to the animation
Whenever, I upload the result file to Telegram, it gets rendered as GIF instead of Video as there's no audio

**Comment by sathyamoorthyrr** [comment]
@tdpetrou would 2nd point above meaningful?

**Comment by sathyarr** [comment]
@tdpetrou When will these changes be released? 🙄

**Comment by sathyarr** [comment]
@tdpetrou Been an year. will this be released?

**Comment by niknah** [comment]
I did this by have two rows with the same data one after an other.  So there is one interval where it animates and one where it sits there and pauses.
