### ISSUE TITLE
Change background color, outside chart 

### ISSUE THREAD

**Issue by techavarria** [dexplo/bar_chart_race#22]
When trying to change the background color by passing the matplotlib fig, the background inside the axes is changed but outside isn't. 

![image](https://user-images.githubusercontent.com/37666869/88067542-bd20c200-cb34-11ea-8442-0678d1cb4d07.png)

**Comment by tdpetrou** [comment]
Can you post the code that you used to create this? This may have to do with how matplotlib requires its users to use the current background color even if its already set when saving.

**Comment by tdpetrou** [comment]
Just fixed this. I needed to add `savefig_kwargs` in the `animation.save` method. Thank you for reporting the issue!

**Comment by ahmetakil** [comment]
Hi is there a chance that I can see the code that changes the background color I tried to use fig= parameter but I wasn't quite able to figure it out

**Comment by starfriend10** [comment]
Same as @ahmetakil, anyone can help to tell an example to set the background color (inside, not outside)? Thanks.
Edits: Okay, I'm managed to achieve it by changing the source code in "prepare_axes" section.
