### ISSUE TITLE
Bars Overlap Each Other During Animation

### ISSUE THREAD

**Issue by andresberejnoi** [dexplo/bar_chart_race#23]
Hello, I have been trying this library to animate data I collected about my puppies while they were growing. However, I have a problem where many of the bars overlap with each other. 

The dataset has 9 different dogs, and about 200 data points per dog (there are many NaN values in between). Do you have any suggestions about what could be the issue?

**Comment by andresberejnoi** [comment]
Could it be the NaN values messing with the code?

**Comment by kuharan** [comment]
Try using df.fillna(method='ffill') and df.fillna(method='bfill') or interpolation ; whichever works best for your case.

**Comment by tdpetrou** [comment]
Hi Andres, I haven't really tested data with lots of missing values and as @kuharan mentioned, its best to fill them in before doing the race. Can you attach the dataset here in a separate post (or link to it)? Thanks!

**Comment by andresberejnoi** [comment]
Thanks. I tested by just filling all missing values with interpolation and the problem was solved. I will close this issue. I have another question about using images for lables, but I think I will open a separate issue for that.
