### ISSUE TITLE
Maybe a have a preview / draft keyword argument

### ISSUE THREAD

**Issue by ahuang11** [dexplo/bar_chart_race#5]
Nice package! One suggestion I have is to have a preview keyword that either only does the head of the pandas dataframe or have it skip half the frames because after taking a while to export the gif, I realized the labels were all crammed and the data doesn't really start until a later date (i.e. the bars were all at 0).

**Comment by tdpetrou** [comment]
Hey Andrew,

I would suggest using the `DataFrame.head` method before passing in the
entire DataFrame. You can also change the figsize and labelsize..
