### ISSUE TITLE
Trying df = bcr.load_dataset('urban_pop') -> ValueError: 'date' is not in list

### ISSUE THREAD

**Issue by leifulstrup** [dexplo/bar_chart_race#7]
Context: Colab Notebook

df = bcr.load_dataset('urban_pop')
df

ValueError                                Traceback (most recent call last)
<ipython-input-14-da41c5e250c0> in <module>()
----> 1 df = bcr.load_dataset('urban_pop')
      2 df

7 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in _set(x)
   2003 
   2004             if not is_integer(x):
-> 2005                 x = names.index(x)
   2006 
   2007             self._reader.set_noconvert(x)

ValueError: 'date' is not in list

**Comment by tdpetrou** [comment]
Thanks for reporting this! Just fixed in master.
