### ISSUE TITLE
OSX Catalina Version 10.15.4 error -> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by leifulstrup** [dexplo/bar_chart_race#8]
Context: macOS OSX Catalina Version 10.15.4
- Anaconda (latest using 3.7)

MovieWriter stderr:
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
_______
Looks like a Mac OS configuration issue. Have tried reinstalling FFmpeg via
brew reinstall FFmpeg per # see this link - https://stackoverflow.com/questions/60745450/trouble-with-ffmpeg-on-mac-os-catalina-10-15-3

I don't think it has to do with your code but something about this matplotlib.animation library and latest version of OSX issues.

Your code works great via Colab. Great package. Thank you for creating this

**Comment by tdpetrou** [comment]
Make can explicitly point to the ffmpeg path with `plt.rcParams['ffmpeg_path'] = /path/to/ffmpeg`. Can you try that and see if it works?

**Comment by leifulstrup** [comment]
I got it working. Steps:

(1) Followed homebrew instructions to remove homebrew
(3) Restarted machine
(2) Installed homebrew (fresh)
(4) Installed ffmpeg via homebrew (brew install ffmpeg)

**Comment by tdpetrou** [comment]
Thanks for reporting on this. I will add this to the docs for mac as its the easiest option to get ffmpeg installed.

**Comment by amrrs** [comment]
@tdpetrou I tried to explicitly mention the `ffmpeg` path and still I'm facing this error

**Comment by tdpetrou** [comment]
Added a small section to the docs about homebrew. https://www.dexplo.org/bar_chart_race/installation/#installing-ffmpeg
