### ISSUE TITLE
Index location - make adjustable?

### ISSUE THREAD

**Issue by thecraigd** [dexplo/bar_chart_race#9]
First of all, thanks for putting this together, it's a really easy-to-use and effective way to produce a good-looking bar chart race. 

Is it possible to make the location of the index when use_index=True adjustable? For [the video I created](https://github.com/thecraigd/Bar_Chart_Race/blob/master/income.mp4) the index (in this case the year) overlaps with the bottom bars.

This is the code I used in Jupyter. The [full Notebook](https://github.com/thecraigd/Bar_Chart_Race/blob/master/income-bar-chart-race-package.ipynb) is [here](https://github.com/thecraigd/Bar_Chart_Race/blob/master/income-bar-chart-race-package.ipynb)

```bcr.bar_chart_race(
    df=income_new,
    filename='income.mp4',
    period_length=250,
    title='GDP per capita (in 2011 USD)',
    n_bars=10)
```

This is just a suggestion for an improvement. If there were an argument that could be passed with a few different options (eg right, centre, left, upper_right, lower_right) that would allow the user to avoid this issue. 

Thanks again for your work on this package.

**Comment by tdpetrou** [comment]
Thanks for using bar_chart_race! I just released a new version with a huge number of options. You can place a label on the graph exactly where you want it, format it with date directives or new-style string formatting and even place more custom text for each frame. 

Check out the tutorial in the docs for the full rundown. www.dexplo.org/bar_chart_race
